using System.Windows;
using System.Windows.Controls;
using AlgoTrading;

namespace PresentationLayer
{
    /// <summary>
    /// Interaction logic for CancelRequest.xaml
    /// </summary>
    public partial class Cancel_Request : Page
    {
        MarketClientOptions UserOptions;
        public Cancel_Request()
        {
            InitializeComponent();
            this.WindowTitle = this.Title;
            UserOptions = new MarketClientOptions();
        }

        private void Back_Click(object sender, RoutedEventArgs e)
        {
            ((Window)this.Parent).Content = new Requests(); 
        }

        private void Send_Click(object sender, RoutedEventArgs e)
        {
            int id = Parser.ReadIntString(idInput, Result);
            bool check = false;
            if (id != -1)//check if the input is legal
            {
                check = UserOptions.SendCancelBuySellRequest(int.Parse(idInput.Text));
                if (check) Result.Content = "Canceled Succesfully!";
                else Result.Content = "Wrong id";
            }
        }

        //delete all the user active requests
        private void Delete_All_Click(object sender, RoutedEventArgs e)
        {
            //delete.Content = System.Drawing.Color.Pink;
            Result.Content = "Canceling..";
            bool check = UserOptions.DeleteEveryActiveRequest();
            if (check) Result.Content = "Canceled all Succesfully!";
            else Result.Content = "Some of the active requests has already been performed";
        }

        //delete all the user active requests, that was not generated by ama
        private void UnAma_Delete_Click(object sender, RoutedEventArgs e)
        {
            Result.Content = "Canceling..";
            bool check = UserOptions.DeleteEveryUnAMAActiveRequest();
            if (check) Result.Content = "Canceled all Succesfully!";
            else Result.Content = "Some of the active requests has already been performed";
        }

        //delete all the user active requests, that generated by ama
        private void Ama_Delete_Click(object sender, RoutedEventArgs e)
        {
            Result.Content = "Canceling..";
            bool check = UserOptions.DeleteEveryAMAActiveRequest();
            if (check) Result.Content = "Canceled all Succesfully!";
            else Result.Content = "Some of the active requests has already been performed";
        }
    }
}
